name: aggregator_connector
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  input_slider: ^0.3.1
  provider: ^6.1.1
  web_socket_channel: ^2.4.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
